import colors from "./colors";

const lightColors = {
  "background-1": colors.WHITE,
  "background-2": colors.GRAY[200],
  "background-3": colors.GRAY[500],
  "background-inverse-1": colors.BLACK,
  "background-inverse-2": colors.GRAY[1100],
  "background-inverse-3": colors.GRAY[800],
  "layer-1": colors.WHITE,
  "layer-2": colors.GRAY[100],
  "layer-3": colors.GRAY[200],
  "layer-disabled": colors.GRAY[300],
  "layer-highlight-light": colors.PRIMARY[100],
  "layer-inverse-1": colors.BLACK,
  "layer-inverse-2": colors.GRAY[1300],
  "layer-inverse-3": colors.GRAY[1200],
  "content-1": colors.BLACK,
  "content-2": colors.GRAY[1000],
  "content-3": colors.GRAY[800],
  "content-disabled": colors.GRAY[300],
  "content-primary": colors.PRIMARY[800],
  "content-primary-dark": colors.PRIMARY[1000],
  "content-primary-light": colors.PRIMARY[400],
  "content-secondary": colors.SECONDARY[800],
  "content-secondary-dark": colors.SECONDARY[1200],
  "content-secondary-light": colors.SECONDARY[400],
  "content-inverse-1": colors.WHITE,
  "content-inverse-2": colors.GRAY[300],
  "content-inverse-3": colors.GRAY[700],
  "link-primary": colors.LINK,
  "link-active": colors.LINK,
  "link-disabled": colors.GRAY[700],
  "border-1": colors.GRAY[1300],
  "border-2": colors.GRAY[900],
  "border-3": colors.GRAY[600],
  "border-disabled": colors.GRAY[700],
  "border-primary": colors.PRIMARY[600],
  "border-secondary": colors.SECONDARY[800],
  "border-inverse-1": colors.GRAY[100],
  "border-inverse-2": colors.GRAY[300],
  "border-inverse-3": colors.GRAY[500],
  "semantic-success": colors.SEMANTIC.SUCCESS,
  "semantic-error": colors.SEMANTIC.ERROR,
  "semantic-warning": colors.SEMANTIC.WARNING,
  "semantic-info": colors.SEMANTIC.INFO,
};

export default lightColors;
