import colors from "./colors";

const lightColors = {
  "background-1": colors.white,
  "background-2": colors.gray[100],
  "background-3": colors.gray[200],
  "background-inverse-1": colors.black,
  "background-inverse-2": colors.gray[1300],
  "background-inverse-3": colors.gray[1200],
  "layer-1": colors.white,
  "layer-2": colors.gray[100],
  "layer-3": colors.gray[200],
  "layer-disabled": colors.gray[300],
  "layer-inverse-1": colors.black,
  "layer-inverse-2": colors.gray[1300],
  "layer-inverse-3": colors.gray[1200],
  "content-1": colors.black,
  "content-2": colors.gray[1000],
  "content-3": colors.gray[800],
  "content-disabled": colors.gray[300],
  "content-primary": colors.PRIMARY[800],
  "content-primary-dark": colors.PRIMARY[1200],
  "content-primary-light": colors.PRIMARY[400],
  "content-secondary": colors.SECONDARY[800],
  "content-secondary-dark": colors.SECONDARY[1200],
  "content-secondary-light": colors.SECONDARY[400],
  "content-inverse-1": colors.white,
  "content-inverse-2": colors.gray[300],
  "content-inverse-3": colors.gray[700],
  "link-primary": colors.link,
  "link-active": colors.link,
  "link-disabled": colors.gray[700],
  "border-1": colors.gray[1300],
  "border-2": colors.gray[900],
  "border-3": colors.gray[600],
  "border-disabled": colors.gray[700],
  "border-primary": colors.PRIMARY[800],
  "border-secondary": colors.SECONDARY[800],
  "border-inverse-1": colors.gray[100],
  "border-inverse-2": colors.gray[300],
  "border-inverse-3": colors.gray[500],
  "semantic-success": colors.semantic.success,
  "semantic-error": colors.semantic.error,
  "semantic-warning": colors.semantic.warning,
  "semantic-info": colors.semantic.info,
};

export default lightColors;
