import colors from "@styles/themes/colors";

const lightColors = {
  "background-1": colors.white,
  "background-2": colors.gray[100],
  "background-3": colors.gray[200],
  "background-inverse-1": colors.black,
  "background-inverse-2": colors.gray[1300],
  "background-inverse-3": colors.gray[1200],
  "layer-1": colors.white,
  "layer-2": colors.gray[100],
  "layer-3": colors.gray[200],
  "layer-disabled": colors.gray[300],
  "layer-inverse-1": colors.black,
  "layer-inverse-2": colors.gray[1300],
  "layer-inverse-3": colors.gray[1200],
  "content-1": colors.white,
  "content-2": colors.gray[200],
  "content-3": colors.gray[400],
  "content-disabled": colors.gray[300],
  "content-primary": colors.primary[800],
  "content-primary-dark": colors.primary[1200],
  "content-primary-light": colors.primary[400],
  "content-secondary": colors.secondary[800],
  "content-secondary-dark": colors.secondary[1200],
  "content-secondary-light": colors.secondary[400],
  "content-inverse-1": colors.black,
  "content-inverse-2": colors.gray[1300],
  "content-inverse-3": colors.gray[1200],
  "text-1": colors.gray[1300],
  "text-2": colors.gray[1100],
  "text-3": colors.gray[900],
  "text-primary": colors.primary[800],
  "text-primary-dark": colors.primary[1200],
  "text-primary-light": colors.primary[400],
  "text-secondary": colors.secondary[800],
  "text-secondary-dark": colors.secondary[1200],
  "text-secondary-light": colors.secondary[400],
  "text-inverse-1": colors.gray[100],
  "text-inverse-2": colors.gray[300],
  "text-inverse-3": colors.gray[500],
  "text-disabled": colors.gray[700],
  "link-primary": colors.link,
  "link-active": colors.link,
  "link-disabled": colors.gray[700],
  "border-1": colors.gray[1300],
  "border-2": colors.gray[1100],
  "border-3": colors.gray[900],
  "border-disabled": colors.gray[700],
  "border-primary": colors.primary[800],
  "border-secondary": colors.secondary[800],
  "border-inverse-1": colors.gray[100],
  "border-inverse-2": colors.gray[300],
  "border-inverse-3": colors.gray[500],
  "semantic-success": colors.semantic.success,
  "semantic-error": colors.semantic.error,
  "semantic-warning": colors.semantic.warning,
  "semantic-info": colors.semantic.info,
};

export default lightColors;
