export const temp = [
  {
    id: 0,
    title: "밋펫",
    startDate: "2023.01",
    endDate: "2023.08",
    status: "present",
    role: "Frontend Developer",
    subtitle: "반려동물 안심 입양 플랫폼",
    tags: ["WEB", "Next.js"],
    thumbnail: "",
    key: "meetpet",
  },
  {
    id: 1,
    title: "새폴더",
    startDate: "2023.09",
    endDate: "",
    status: "inProgress",
    role: "Frontend Developer",
    subtitle: "함께하는 탐조 생활",
    tags: ["APP", "React Native"],
    thumbnail: "",
    key: "sae-folder",
  },
  {
    id: 2,
    title: "SILVERBI 블로그",
    status: "present",
    startDate: "2024.03",
    endDate: "",
    role: "Frontend Developer",
    subtitle: "",
    tags: ["WEB", "Next.js", "NestJS"],
    thumbnail: "",
    key: "silverbi-blog",
  },
  {
    id: 3,
    title: "미슐랭면",
    status: "backlog",
    startDate: "",
    endDate: "",
    role: "Frontend Developer",
    subtitle: "나만의 맛있는 평양냉면 찾기",
    tags: ["WEB", "React"],
    thumbnail: "",
    key: "michelin-noodle",
  },
  {
    id: 4,
    title: "아이디코",
    status: "present",
    startDate: "2023.05",
    endDate: "",
    role: "Frontend Developer",
    subtitle: "세상에 하나 뿐인 코로 만든 강아지 ID",
    tags: ["APP", "React Native"],
    thumbnail: "",
    key: "idco",
  },
  {
    id: 5,
    title: "마이드림",
    status: "backlog",
    startDate: "",
    endDate: "",
    role: "Frontend Developer",
    subtitle: "",
    tags: ["WEB", "Next.js"],
    thumbnail: "",
    key: "mydream",
  },
];
