export const ImageTypes = {
  LANDING_THUMBNAIL: "LANDING_THUMBNAIL",
  TECH_THUMBNAIL: "TECH_THUMBNAIL",
  PROFILE_CHARACTER: "PROFILE_CHARACTER",
  PROJECT_MEETPET: "PROJECT_MEETPET",
  PROJECT_IDCO: "PROJECT_IDCO",
  PROJECT_SAEFOLDER: "PROJECT_SAEFOLDER",
  PROJECT_DEEPFALL: "PROJECT_DEEPFALL",
  PROJECT_MICHELINMYEON: "PROJECT_MICHELINMYEON",
  PROJECT_SILVERBI_BLOG: "PROJECT_SILVERBI_BLOG",
  PROJECTS_THUMBNAIL: "PROJECTS_THUMBNAIL",
  RETROSPECT_THUMBNAIL: "RETROSPECT_THUMBNAIL",
  HAND_JAR: "HAND_JAR",
  ERROR_BACKGROUND: "ERROR_BACKGROUND",
} as const;
export type ImageTypes = (typeof ImageTypes)[keyof typeof ImageTypes];
