import { SkeletonTheme } from "react-loading-skeleton";
import SessionProvider from "@layouts/sessionProvider";
import themes from "@styles/themes";
import localFont from "next/font/local";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({ children, modal }: { modal: React.ReactNode; children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body suppressHydrationWarning={true} className={`${pretendard.variable} font-pretendard`}>
        <SessionProvider>
          <SkeletonTheme
            baseColor={themes.colors.light["layer-3"]}
            highlightColor={themes.colors.light["layer-disabled"]}
          >
            {modal}
            <main>{children}</main>
          </SkeletonTheme>
        </SessionProvider>
      </body>
    </html>
  );
}
