export const metadata = {
  title: 'Silverbi Blog',
  description: 'Generated by silverbi',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}
