import "@styles/globals.css";
import { ThemeProvider } from "context/ThemeProvider";
import SessionProvider from "context/sessionProvider";
import localFont from "next/font/local";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const pretendard = localFont({
  src: "../public/assets/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({ children, modal }: { modal: React.ReactNode; children: React.ReactNode }) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body suppressHydrationWarning={true} className={`${pretendard.variable} font-pretendard`}>
        <SessionProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {modal}
            <main>{children}</main>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
