#!/bin/bash
current_branch=$(git symbolic-ref --short HEAD)


# Run lint:fix and test scripts
if ! (echo "Running ESLint..." && yarn run lint:fix) ; then
  echo "Linting failed, push not allowed"
  exit 1
fi 